name: seizure_spread
channels:
 - defaults
dependencies:
 - python=3.8
 - numpy=1.19.*
 - pandas=1.0.*
 - scipy=1.5.*
 - pip
 - pip:
   - tensorflow==2.2.*
   - fury==0.6.*
   - matplotlib==3.3.*
   - seaborn==0.11.*
   - scikit-learn==0.23.*
   - deprecation==2.1.0 #download iEEG.org data
   - requests==2.23.0 #download iEEG.org data
   - pennprov==2.2.9 #download iEEG.org data
   - xlrd==1.2.* #read excell xlsx files